commerce_payment.commerce_payment_gateway.plugin.paymetric:
  type: commerce_payment_gateway_configuration
  mapping:
    xipay_url:
      type: string
      label: 'XiPay URL'
    xipay_user:
      type: string
      label: 'XiPay User ID'
    xipay_password:
      type: string
      label: 'XiPay Password'
    xiintercept_GUID:
      type: string
      label: 'XiIntercept GUID'
    xiintercept_PSK:
      type: string
      label: 'XiIntercept PSK'
    xiintercept_url:
      type: uri
      label: 'XiIntercept URL'
    xipay_merchantid:
      type: string
      label: 'XiPay Merchant ID'
    card_types:
      type: string
      label: 'Limit accepted credit cards to the following types'
    transaction_type:
      type: radios
      label: 'Default credit card transaction type'